name: Close Stale Pull Requests

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  close_stale_prs:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      issues: write

    steps:
      - name: Close stale pull requests
        uses: actions/stale@v5
        with:
          stale-pr-message: >
            This pull request has been marked as stale because it has been inactive
            for more than 14 days. Please update this pull request or it will be
            automatically closed in 7 days.
          days-before-stale: 14
          days-before-close: 0
          stale-pr-label: stale

          # Issue settings (disabled)
          days-before-issue-stale: -1
          days-before-issue-close: -1

          # Only process pull requests, not issues
          only-pr-labels: "*"
